from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/dna-seq-varlociraptor as a module
module dna_seq_varlociraptor:
    snakefile: 
        github("snakemake-workflows/dna-seq-varlociraptor", path="workflow/Snakefile", tag="v5.8.3")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/dna-seq-varlociraptor
use rule * from dna_seq_varlociraptor
